services:
  - type: web_service
    name: flately-backend
    env: node
    region: oregon
    plan: starter
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
